//
// Created by Oyekunle Oloyede on 28/10/2020.
//

#ifndef TRINCETC_READNUMBERANDFINDAVERAGE_H
#define TRINCETC_READNUMBERANDFINDAVERAGE_H

void readAndFindAverage();

#endif //TRINCETC_READNUMBERANDFINDAVERAGE_H
